---
name: Test

on:
  workflow_dispatch:
permissions: read-all

jobs:
  alert-and-report:
    name: Alert & Create Report
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Find existing drift issue
        id: find_drift_report
        uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3
        with:
          actions: find-issues
          issue-state: "open"
          create-issue-if-not-exist: "true"
          show-thanks: "false"
          title-includes: "Report"
          labels: "alert"
          body-includes: |
            ## Drift Detection Alert

            Find ifnot create

#      - name: Update drift issue if present
#        if: steps.find_drift_report.outputs.issues != '[]'
#        uses: actions-cool/issues-helper@a610082f8ac0cf03e357eb8dd0d5e2ba075e017e # v3
#        with:
#          actions: "update-issue"
#          show-thanks: "false"
#          issue-number: "${{ fromJSON(steps.find_drift_report.outputs.issues)[0].number }}""
#          update-mode: "append"
#          body: |
#            Drift still present as of this run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}