---
name: Test

on:
  workflow_dispatch:
permissions: read-all

jobs:
  alert-and-report:
    name: Alert & Create Report
    permissions:
      issues: write
    runs-on: ubuntu-latest
    steps:
      - name: Find existing drift issue
        id: find_drift_report
        uses: actions-cool/issues-helper@v3.6.2
        with:
          actions: find-issues
          issue-state: "open"
          create-issue-if-not-exist: "true"
          show-thanks: "false"
          title-includes: "Report"
          labels: "alert"
          body-includes: |
            ## Drift Detection Alert
            - [View Action Run](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})
            Find if not create

      - name: Update drift issue if present
        if: steps.find_drift_report.outputs.issues != '[]'
        uses: actions-cool/issues-helper@v3.6.2
        with:
          actions: update-issue
          show-thanks: "false"
          issue-number: "${{ fromJSON(steps.find_drift_report.outputs.issues)[0].number }}"
          update-mode: "append"
          body: |
            update